using System.Collections.Generic;

namespace UsStateMapper {
  public interface IStateNameLookup {
    string FindState(string normalizedStateText);
  }

  public class StateNameLookup : IStateNameLookup {
    public string FindState(string normalizedStateText) {
      string state;
      var found = Lookup.TryGetValue(normalizedStateText, out state);
      return found ? state : string.Empty;
    }
    private static readonly Dictionary<string, string> Lookup = new Dictionary<string, string> {
      {"al", "Alabama"},
      {"alabama", "Alabama"},
      {"01", "Alabama"},
      {"alaska", "Alaska"},
      {"ak", "Alaska"},
      {"02", "Alaska"},
      {"arizona", "Arizona"},
      {"az", "Arizona"},
      {"04", "Arizona"},
      {"arkansas", "Arkansas"},
      {"ar", "Arkansas"},
      {"05", "Arkansas"},
      {"california", "California"},
      {"ca", "California"},
      {"06", "California"},
      {"colorado", "Colorado"},
      {"co", "Colorado"},
      {"08", "Colorado"},
      {"connecticut", "Connecticut"},
      {"ct", "Connecticut"},
      {"09", "Connecticut"},
      {"delaware", "Delaware"},
      {"de", "Delaware"},
      {"10", "Delaware"},
      {"florida", "Florida"},
      {"fl", "Florida"},
      {"12", "Florida"},
      {"georgia", "Georgia"},
      {"ga", "Georgia"},
      {"13", "Georgia"},
      {"hawaii", "Hawaii"},
      {"hi", "Hawaii"},
      {"15", "Hawaii"},
      {"idaho", "Idaho"},
      {"id", "Idaho"},
      {"16", "Idaho"},
      {"illinois", "Illinois"},
      {"il", "Illinois"},
      {"17", "Illinois"},
      {"indiana", "Indiana"},
      {"in", "Indiana"},
      {"18", "Indiana"},
      {"iowa", "Iowa"},
      {"ia", "Iowa"},
      {"19", "Iowa"},
      {"kansas", "Kansas"},
      {"ks", "Kansas"},
      {"20", "Kansas"},
      {"kentucky", "Kentucky"},
      {"ky", "Kentucky"},
      {"21", "Kentucky"},
      {"louisiana", "Louisiana"},
      {"la", "Louisiana"},
      {"22", "Louisiana"},
      {"maine", "Maine"},
      {"me", "Maine"},
      {"23", "Maine"},
      {"maryland", "Maryland"},
      {"md", "Maryland"},
      {"24", "Maryland"},
      {"massachusetts", "Massachusetts"},
      {"ma", "Massachusetts"},
      {"25", "Massachusetts"},
      {"michigan", "Michigan"},
      {"mi", "Michigan"},
      {"26", "Michigan"},
      {"minnesota", "Minnesota"},
      {"mn", "Minnesota"},
      {"27", "Minnesota"},
      {"mississippi", "Mississippi"},
      {"ms", "Mississippi"},
      {"28", "Mississippi"},
      {"missouri", "Missouri"},
      {"mo", "Missouri"},
      {"29", "Missouri"},
      {"montana", "Montana"},
      {"mt", "Montana"},
      {"30", "Montana"},
      {"nebraska", "Nebraska"},
      {"ne", "Nebraska"},
      {"31", "Nebraska"},
      {"nevada", "Nevada"},
      {"nv", "Nevada"},
      {"32", "Nevada"},
      {"newhampshire", "New Hampshire"},
      {"nh", "New Hampshire"},
      {"33", "New Hampshire"},
      {"newjersey", "New Jersey"},
      {"nj", "New Jersey"},
      {"34", "New Jersey"},
      {"newmexico", "New Mexico"},
      {"nm", "New Mexico"},
      {"35", "New Mexico"},
      {"newyork", "New York"},
      {"ny", "New York"},
      {"36", "New York"},
      {"northcarolina", "North Carolina"},
      {"nc", "North Carolina"},
      {"37", "North Carolina"},
      {"northdakota", "North Dakota"},
      {"nd", "North Dakota"},
      {"38", "North Dakota"},
      {"ohio", "Ohio"},
      {"oh", "Ohio"},
      {"39", "Ohio"},
      {"oklahoma", "Oklahoma"},
      {"ok", "Oklahoma"},
      {"40", "Oklahoma"},
      {"oregon", "Oregon"},
      {"or", "Oregon"},
      {"41", "Oregon"},
      {"pennsylvania", "Pennsylvania"},
      {"pa", "Pennsylvania"},
      {"42", "Pennsylvania"},
      {"rhodeisland", "Rhode Island"},
      {"ri", "Rhode Island"},
      {"44", "Rhode Island"},
      {"southcarolina", "South Carolina"},
      {"sc", "South Carolina"},
      {"45", "South Carolina"},
      {"southdakota", "South Dakota"},
      {"sd", "South Dakota"},
      {"46", "South Dakota"},
      {"tennessee", "Tennessee"},
      {"tn", "Tennessee"},
      {"47", "Tennessee"},
      {"texas", "Texas"},
      {"tx", "Texas"},
      {"48", "Texas"},
      {"utah", "Utah"},
      {"ut", "Utah"},
      {"49", "Utah"},
      {"vermont", "Vermont"},
      {"vt", "Vermont"},
      {"50", "Vermont"},
      {"virginia", "Virginia"},
      {"va", "Virginia"},
      {"51", "Virginia"},
      {"washington", "Washington"},
      {"wa", "Washington"},
      {"53", "Washington"},
      {"westvirginia", "West Virginia"},
      {"wv", "West Virginia"},
      {"54", "West Virginia"},
      {"wisconsin", "Wisconsin"},
      {"wi", "Wisconsin"},
      {"55", "Wisconsin"},
      {"wyoming", "Wyoming"},
      {"wy", "Wyoming"},
      {"56", "Wyoming"},
      {"districtofcolumbia", "District of Columbia"},
      {"dc", "District of Columbia"},
      {"11", "District of Columbia"},
      {"americansamoa", "American Samoa"},
      {"as", "American Samoa"},
      {"60", "American Samoa"},
      {"guam", "Guam"},
      {"gu", "Guam"},
      {"66", "Guam"},
      {"northernmarianaislands", "Northern Mariana Islands"},
      {"mp", "Northern Mariana Islands"},
      {"69", "Northern Mariana Islands"},
      {"puertorico", "Puerto Rico"},
      {"pr", "Puerto Rico"},
      {"72", "Puerto Rico"},
      {"usvirginislands", "U.S. Virgin Islands"},
      {"vi", "U.S. Virgin Islands"},
      {"78", "U.S. Virgin Islands"},
    };
  }
}
