using System.Collections.Generic;

namespace UsStateMapper {
  public interface IStateNameLookup {
    string FindState(string normalizedStateText);
  }

  public class StateNameLookup : IStateNameLookup {
    public string FindState(string normalizedStateText) {
      return Lookup[normalizedStateText];
    }
    private static readonly Dictionary<string, string> Lookup = new Dictionary<string, string> {
      {"al", "Alabama"},
      {"alabama", "Alabama"},
      {"alaska", "Alaska"},
      {"ak", "Alaska"},
      {"arizona", "Arizona"},
      {"az", "Arizona"},
      {"arkansas", "Arkansas"},
      {"ar", "Arkansas"},
      {"california", "California"},
      {"ca", "California"},
      {"colorado", "Colorado"},
      {"co", "Colorado"},
      {"connecticut", "Connecticut"},
      {"ct", "Connecticut"},
      {"delaware", "Delaware"},
      {"de", "Delaware"},
      {"florida", "Florida"},
      {"fl", "Florida"},
      {"georgia", "Georgia"},
      {"ga", "Georgia"},
      {"hawaii", "Hawaii"},
      {"hi", "Hawaii"},
      {"idaho", "Idaho"},
      {"id", "Idaho"},
      {"illinois", "Illinois"},
      {"il", "Illinois"},
      {"indiana", "Indiana"},
      {"in", "Indiana"},
      {"iowa", "Iowa"},
      {"ia", "Iowa"},
      {"kansas", "Kansas"},
      {"ks", "Kansas"},
      {"kentucky", "Kentucky"},
      {"ky", "Kentucky"},
      {"louisiana", "Louisiana"},
      {"la", "Louisiana"},
      {"maine", "Maine"},
      {"me", "Maine"},
      {"maryland", "Maryland"},
      {"md", "Maryland"},
      {"massachusetts", "Massachusetts"},
      {"ma", "Massachusetts"},
      {"michigan", "Michigan"},
      {"mi", "Michigan"},
      {"minnesota", "Minnesota"},
      {"mn", "Minnesota"},
      {"mississippi", "Mississippi"},
      {"ms", "Mississippi"},
      {"missouri", "Missouri"},
      {"mo", "Missouri"},
      {"montana", "Montana"},
      {"mt", "Montana"},
      {"nebraska", "Nebraska"},
      {"ne", "Nebraska"},
      {"nevada", "Nevada"},
      {"nv", "Nevada"},
      {"newhampshire", "New Hampshire"},
      {"nh", "New Hampshire"},
      {"newjersey", "New Jersey"},
      {"nj", "New Jersey"},
      {"newmexico", "New Mexico"},
      {"nm", "New Mexico"},
      {"newyork", "New York"},
      {"ny", "New York"},
      {"northcarolina", "North Carolina"},
      {"nc", "North Carolina"},
      {"northdakota", "North Dakota"},
      {"nd", "North Dakota"},
      {"ohio", "Ohio"},
      {"oh", "Ohio"},
      {"oklahoma", "Oklahoma"},
      {"ok", "Oklahoma"},
      {"oregon", "Oregon"},
      {"or", "Oregon"},
      {"pennsylvania", "Pennsylvania"},
      {"pa", "Pennsylvania"},
      {"rhodeisland", "Rhode Island"},
      {"ri", "Rhode Island"},
      {"southcarolina", "South Carolina"},
      {"sc", "South Carolina"},
      {"southdakota", "South Dakota"},
      {"sd", "South Dakota"},
      {"tennessee", "Tennessee"},
      {"tn", "Tennessee"},
      {"texas", "Texas"},
      {"tx", "Texas"},
      {"utah", "Utah"},
      {"ut", "Utah"},
      {"vermont", "Vermont"},
      {"vt", "Vermont"},
      {"virginia", "Virginia"},
      {"va", "Virginia"},
      {"washington", "Washington"},
      {"wa", "Washington"},
      {"westvirginia", "West Virginia"},
      {"wv", "West Virginia"},
      {"wisconsin", "Wisconsin"},
      {"wi", "Wisconsin"},
      {"wyoming", "Wyoming"},
      {"wy", "Wyoming"},
      {"districtofcolumbia", "District of Columbia"},
      {"dc", "District of Columbia"},
      {"americansamoa", "American Samoa"},
      {"as", "American Samoa"},
      {"guam", "Guam"},
      {"gu", "Guam"},
      {"northernmarianaislands", "Northern Mariana Islands"},
      {"mp", "Northern Mariana Islands"},
      {"puertorico", "Puerto Rico"},
      {"pr", "Puerto Rico"},
      {"usvirginislands", "U.S. Virgin Islands"},
      {"vi", "U.S. Virgin Islands"},
    };

  }
}
